AWSTemplateFormatVersion: "2010-09-09"
Description: VPC

Parameters:
  VpcName:
    Type: String
    Description: Vpc name

  Environment:
    Type: String
    AllowedValues: [prod, uat, dev]
    Default: dev
    Description: Target environment

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR

  PublicSubnetName:
    Type: String
    Description: Public subnet name

  PrivateSubnetName:
    Type: String
    Description: Private subnet name

  SubnetCidr:
    Type: String
    Default: 10.0.1.0/24
    Description: Subnet CIDR

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName
        - Key: Environnement
          Value: !Ref Environment

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref SubnetCidr  # 10.0.1.0/24 par exemple
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref PublicSubnetName
        - Key: Environment
          Value: !Ref Environment

  FirstPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${PrivateSubnetName}-a"
        - Key: Environment
          Value: !Ref Environment

  SecondPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [ 2, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${PrivateSubnetName}-b"
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${VpcName}-igw"
        - Key: Environment
          Value: !Ref Environment

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Sub "${VpcName}-rtb"
        - Key: Environment
          Value: !Ref Environment

  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

Outputs:
  VpcCidr:
    Description: Cidr du VPC created
    Value: !Ref Vpc

  VpcId:
    Description: VPC ID created
    Value: !Ref Vpc
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"

  PublicSubnetId:
    Description: Public subnet ID
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetId"

  FirstPrivateSubnetId:
    Description: First private subnet ID
    Value: !Ref FirstPrivateSubnet
    Export:
      Name: !Sub "${AWS::StackName}-FirstPrivateSubnetId"

  SecondPrivateSubnetId:
    Description: Second private subnet ID
    Value: !Ref SecondPrivateSubnet
    Export:
      Name: !Sub "${AWS::StackName}-SecondPrivateSubnetId"



