AWSTemplateFormatVersion: "2010-09-09"
Description: Bastion

Parameters:
  Environment:
    Type: String
    AllowedValues: [prod, uat, dev]
    Default: dev
    Description: Environnement cible

  KeyName:
    Type: String
    Description: Nom de la paire de clés EC2 existante

  VpcStackName:
    Type: String
    Description: Nom de la stack VPC à importer

  DevopsPassword:
    Type: String
    NoEcho: true
    Description: Mot de passe pour l'utilisateur devops

Resources:
  BastionSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Bastion SG - only reachable from Bastion
      VpcId:
        !ImportValue
          Fn::Sub: "${VpcStackName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # À restreindre pour la prod
      Tags:
        - Key: Name
          Value: !Sub bastion-${Environment}-sg
        - Key: Environment
          Value: !Ref Environment

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0caad95876a4611ee  # Amazon Linux 2023 (Paris)
      SubnetId:
        !ImportValue
          Fn::Sub: "${VpcStackName}-PublicSubnetId"
      SecurityGroupIds:
        - !Ref BastionSG
      Tags:
        - Key: Name
          Value: !Sub bastion-${Environment}
        - Key: Environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y htop git vim
          echo "Welcome to the bastion ${Environment}" > /etc/motd
          useradd devops
          passwd -l devops
          echo 'UserData completed' >> /var/log/userdata.log

Outputs:  
  BastionSG:
    Description: ID du Bastion Security Group
    Value: !Ref BastionSG
    Export:
      Name: !Sub "${AWS::StackName}-BastionSG"